from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEndpoint,HuggingFaceEmbeddings
from langchain_contextual import ContextualCompressionRetriever
from langchain.retrievers.document_compressors import LLMChainExtractor